### PR TITLE
add taiwan county map

### PR DESCRIPTION
**Pull request by zbryikt**
quickly added a taiwan county level map including 22 administrative division.

### CODE REVIEW

**Comment by VioletVivirand** [comment]
@zbryikt : Hi! Map noob here. Thank you for your contribution! I've also forked this project before I found this pull request, so I think my work is nothing but duplicated now XD

I think the biggest difference between our files is that I choose [ISO_3166-2:TW](https://zh.wikipedia.org/wiki/ISO_3166-2:TW) standard to be the subdivisions codes of Taiwan, and applied them in [`taiwan.csv`](https://github.com/VioletVivirand/datamaps.co/blob/master/public/data/csv/taiwan.csv) and [`taiwan.json`](https://github.com/VioletVivirand/datamaps.co/blob/master/public/data/topo/taiwan.json). [Here is my repo](https://github.com/VioletVivirand/datamaps.co), please take a look at them if you have time.

I'm just curious and wanna ask for your opinion: which is better for clients to use? And I'm also interested in the codes you use, where did you find them? Because I spent a lot of time searching for the answer ^^"

Thank you for your support! Have a nice day 😸

**Comment by caspg** [comment]
@zbryikt I'm also interested which country codes did you use? I'm planning to display information about used codes in the app (not sure where, though). I personally would go for iso codes which @VioletVivirand used.

@zbryikt @VioletVivirand What do you think about a process of adding new maps? Is there anything to do to improve/simplify this process?

Thank you guys for your time 👍

**Comment by zbryikt** [comment]
@VioletVivirand @caspg I just used the romanization of Taiwan county/city name from wikipedia, and made an abbreviation for each that as short as possible, and that's because there is no guideline in datamaps.co for the code of map, and I found most of the code in other maps are two-letter long, so I just tried to be consistent with other maps (but i still have 3 letters long codes due to duplication of codes)

I think ISO3166-2 would be better if there is no special concern of how code should be chosen,
so let's go for @VioletVivirand version.. @VioletVivirand please also make a pull request from your version :)

**Comment by VioletVivirand** [comment]
@zbryikt : Thank you! I just send the #10 pull request.

@caspg : I think this process is easy enough, and I have no idea of how to simplify it 😅 I'm still new to this area, so it took me some time to finish them, especially when editing the codes in the TopoJSON file. It won't be a big problem for a programer, but could be difficult for someone don't know the structure of codes, JSON, GeoJSON, TopoJSON......unless we find an IDE with GUI.

I've used [QGIS](http://www.qgis.org/en/site/) with GeoJSON file before, don't know if it can work with TopoJSON file or not. If it can, maybe it will be one of the solutions 😍

**Comment by caspg** [comment]
@zbryikt @VioletVivirand Yeah I probably should specify in READMe which state codes should be used. @VioletVivirand PR is already merged and live.

Thanks again for your work.

**Pull request closed without merging**
